export enum Permission {
  JOB_CREATE = 'job:create',
  JOB_EDIT = 'job:edit',
  JOB_VIEW = 'job:view',
  JOB_PUBLISH_DIRECT = 'job:publish_direct',
  JOB_APPROVE = 'job:approve',
  JOB_REJECT = 'job:reject',
  CANDIDATE_CREATE = 'candidate:create',
  CANDIDATE_VIEW = 'candidate:view',
  SUBMISSION_CREATE = 'submission:create',
  SUBMISSION_EDIT = 'submission:edit',
  CLIENT_VIEW = 'client:view',
  CLIENT_CREATE = 'client:create',
  CLIENT_DIRECT_ADD = 'client:direct_add',
  CLIENT_EDIT = 'client:edit',
  CLIENT_APPROVE = 'client:approve',
  CLIENT_REJECT = 'client:reject',
  CLIENT_DELETE = 'client:delete',
  TENANT_SETTINGS = 'tenant:settings',
  USER_MANAGE = 'user:manage',
  PLATFORM_MANAGE = 'platform:manage',
  CANDIDATES_SEARCH_ALL_MARKETS = 'candidate:search_all_markets',
  CANDIDATES_SEARCH_ALL_BRANCHES = 'candidate:search_all_branches',
  JOBS_VIEW_ALL_BRANCHES = 'job:view_all_branches',
  BRANCH_ADMIN_MANAGE = 'branch_admin:manage',
}
