const { Client } = require('pg');
const client = new Client({
  connectionString: "postgresql://postgres.zqpxnnsbbqdlhememsyj:EWhbqnM6IWe5IJaV@aws-1-ap-northeast-1.pooler.supabase.com:6543/postgres",
  ssl: { rejectUnauthorized: false }
});

async function fixLastName() {
  try {
    await client.connect();
    
    console.log("1. Setting last_name = 'User' for all users with NULL last_name in Supabase DB...");
    const res = await client.query("UPDATE user_entity SET last_name = 'User' WHERE last_name IS NULL OR last_name = ''");
    console.log("Updated rows:", res.rowCount);

    await client.end();

    console.log("2. Testing authentication for debam@deb.com...");
    const authRes = await fetch("http://127.0.0.1:8080/realms/enfycon-ats/protocol/openid-connect/token", {
      method: "POST",
      headers: { "Content-Type": "application/x-www-form-urlencoded" },
      body: new URLSearchParams({
        client_id: "ats",
        client_secret: "1EXjjhVK0vSZPPS6lX2ajuYptmEIaLOS",
        username: "debam@deb.com",
        password: "password123",
        grant_type: "password"
      })
    });
    const authData = await authRes.json();
    if (authData.access_token) {
      console.log("\n🎉🎉🎉 AUTHENTICATION SUCCESSFUL! ACCESS TOKEN GENERATED BY SUPABASE KEYCLOAK!");
      console.log("Access Token:", authData.access_token.substring(0, 60) + "...");
      console.log("Token Type:", authData.token_type);
      console.log("Expires In:", authData.expires_in, "seconds");
      console.log("Refresh Token:", authData.refresh_token.substring(0, 40) + "...");
    } else {
      console.error("\n❌ Auth response:", authData);
    }

  } catch (err) {
    console.error(err);
  }
}

fixLastName();
